### ISSUE TITLE
Erreur API

### ISSUE THREAD

**Issue by QuentinBubu** [SizeDevv/Simple-Email-Checker#2]
Bonjour,
Voici une erreur que l'on peut rencontrer:
`details=data['details']`
`KeyError: 'details'`
Or, il serait bien de préparer une condition qui justement check si il n'y a pas d'erreur, car la cause est: en réalité:
`The concurrent connection limit has been exceeded.`
```json
{'error': 'The concurrent connection limit has been exceeded.'}
```
Quentin

**Comment by Sim08570** [comment]
L'erreur viens de la ****clé API**** il faut renouvelé 😉

**Comment by QuentinBubu** [comment]
Ok, merci, je pensais pas qu'il fallait que l'on s'en créer une.
